services:
  application:
    profiles:
      - ''
    build:
      context: ./
    container_name: "application"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VITE_DEV_MODE: "false"
      DATABASE_URL: "postgresql+asyncpg://app:app@database:5432/app"
      REDIS_URL: "redis://redis:6379/0"
    restart: unless-stopped
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: "service:vpn"

  database:
    image: postgres:18.1-alpine3.23
    profiles:
      - ''
      - infra
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - app
      interval: 2s
      timeout: 3s
      retries: 40

  redis:
    image: redis:8.4-alpine3.22
    profiles:
      - ''
      - infra
    hostname: cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
    volumes:
      - redis-data:/data

  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - "8000:8585" # Port forward for application happens here
    volumes:
      - gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=openvpn
      - UPDATER_PERIOD=24h
    env_file: .env

volumes:
  db-data: {}
  redis-data: {}
  gluetun-data: {}