services:
  application:
    profiles:
      - ''
    build:
      context: ./
    container_name: "application"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VITE_DEV_MODE: "false"
      DATABASE_URL: "postgresql+asyncpg://app:app@database:5432/app"
      REDIS_URL: "redis://redis:6379/0"
      SAQ_USE_SERVER_LIFESPAN: "false"
    env_file: .env
    ports:
      - "80:8585"
    restart: always
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database:
    image: postgres:18.1-alpine3.23
    profiles:
      - ''
      - infra
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - app
      interval: 2s
      timeout: 3s
      retries: 40

  redis:
    image: redis:8.4-alpine3.22
    profiles:
      - ''
      - infra
    hostname: cache
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
    volumes:
      - redis-data:/data

  worker:
    profiles:
      - ''
    build:
      context: ./
    command: uv run litestar workers run
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DATABASE_URL: "postgresql+asyncpg://app:app@database:5432/app"
      REDIS_URL: "redis://redis:6379/0"
      SAQ_USE_SERVER_LIFESPAN: "false"
    env_file: .env
    restart: always
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db-data: {}
  redis-data: {}